version: "3.8"
services:
  python:
    container_name: python-sut
    image: asangin/python-sut:1.0.0
    build:
      context: .
      target: dev
    working_dir: /work
    entrypoint: /bin/sh
    stdin_open: true
    tty: true
    volumes:
      - ./src:/work
    ports:
      - "5001:5000"